name: "Tests - Download"

on: 
    workflow_dispatch:

    pull_request:
        branches:
            - main
    

jobs:
    test:
        runs-on: ${{ matrix.os }}
        env:
            DEBUG_ON: "True"
        defaults:
            run:
                working-directory: ./
        
        strategy:
            matrix:
                os: [ubuntu-latest]
                python-versions: [3.11]
                
        steps:
            - uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-versions }}
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Install local package
              run: |
                pip install -e .

            - name: Test application code
              run: musescore-downloader https://musescore.com/user/12461571/scores/3291706
            